### ISSUE TITLE
moveend-handlers and geojson layers to be implemented?

### ISSUE THREAD

**Issue by berndhopp** [inventage/leaflet-map#1]
I'd be interested to know if  "moveend"-eventhandlers and geojson layers are going to be implemented in the future sometime? 

best, thanks

**Comment by peschee** [comment]
Hi @berndhopp 

We created this component as a pre-requisite for a workshop we held, so it is nowhere near a complete abstraction around the LeafletJS library. I think implementing the `moveend` event handlers is trivial and I can probably bake it in. Haven't looked at geojson layers.

However: just yesterday I added an implementation of the `map-ready` event, which carries an instance of the leaflet map itself. This should give you quite some flexibility. Maybe you can use that instance to cover your use case?

**Comment by berndhopp** [comment]
👍

**Comment by peschee** [comment]
@berndhopp I will close this issue as the `map-ready` event should cover both your use cases. Can you let me know in case it does not?
